
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: traffic

traffic:
  flemish:
    data-url: "http://miv.opendata.belfla.be/miv/verkeersdata"
    sensor-config-url: "http://miv.opendata.belfla.be/miv/configuratie/xml"
  kafka:
    traffic-event-topic: "traffic-event"
    vehicle-route-change-event-topic: "vehicle-route-change-event"
    vehicle-route-change-advice-topic: "vehicle-route-change-advice"


logging:
  level:
    com:
      github:
        fbascheper: debug
    org:
      springframework:
        kafka: info
    root: warn
